export const CHANGE_DJRADIO_HEADER_LIST = 'djradio/CHANGE_DJRADIO_HEADER_LIST'

export const CHANGE_DJRADIO_RECOMMEND_LIST = 'djradio/CHANGE_DJRADIO_RECOMMEND_LIST'

export const CHANGE_DJRADIO_RAKING_LIST = 'djradio/CHANGE_DJRADIO_RAKING_LIST'