export const CHANGE_SONG_CATEGORY = 'song/CHANGE_SONG_CATEGORY'
export const CHANGE_SONG_CATEGORY_LIST = 'song/CHANGE_SONG_CATEGORY_LIST'
export const CHANGE_SONG_CARTEGORY_NAME = 'song/CHANGE_SONG_CARTEGORY_NAME'